
export class ObjetoTipoDebitosResult {
    ObterDebitosPorTipoDebitoResult: any;

    constructor() {
        this.ObterDebitosPorTipoDebitoResult = {
            Debito: {
                Debito: [
                  {
                    DescricaoServico: 'Postagem do CRLV 2018',
                    ValorAtualizadoFranquia: '19.6400',
                    DataVencimento: '2018-04-13T03:00:00.000Z',
                    DpvatCotas: '',
                    IdDebito: 84677126,
                    Placa: 'ROU8470',
                    IpvaExercicio: -1,
                    IpvaAnterior: -1,
                    LicenciamentoExercicio: 2,
                    LicenciamentoAnterior: -1,
                    TaxaServico: -1,
                    Multas: -1,
                    IpvaParcelamento: -1,
                    TaxaEspecial: -1,
                    TaxaPatio: -1,
                    DpvatExercicio: -1,
                    DpvatAnterior: -1,
                    CodigoServico: 27,
                    Classe: 1,
                    Exercicio: 2018,
                    Parcela: 0,
                    IpvaCotas: '',
                  },
                  {
                    DescricaoServico: 'Licenciamento Anual 2018',
                    ValorAtualizadoFranquia: '157.0800',
                    DataVencimento: '2018-04-13T03:00:00.000Z',
                    DpvatCotas: '',
                    IdDebito: 84677125,
                    Placa: 'ROU8470',
                    IpvaExercicio: -1,
                    IpvaAnterior: -1,
                    LicenciamentoExercicio: 1,
                    LicenciamentoAnterior: -1,
                    TaxaServico: -1,
                    Multas: -1,
                    IpvaParcelamento: -1,
                    TaxaEspecial: -1,
                    TaxaPatio: -1,
                    DpvatExercicio: -1,
                    DpvatAnterior: -1,
                    CodigoServico: 1,
                    Classe: 1,
                    Exercicio: 2018,
                    Parcela: 0,
                    IpvaCotas: '',
                  },
                  {
                    DescricaoServico: 'Seguro DPVAT 2018 Cota Única',
                    ValorAtualizadoFranquia: '71.0800',
                    DataVencimento: '2018-04-13T03:00:00.000Z',
                    DpvatCotas: '20180',
                    IdDebito: 84677123,
                    Placa: 'ROU8470',
                    IpvaExercicio: -1,
                    IpvaAnterior: -1,
                    LicenciamentoExercicio: 1,
                    LicenciamentoAnterior: -1,
                    TaxaServico: -1,
                    Multas: -1,
                    IpvaParcelamento: -1,
                    TaxaEspecial: -1,
                    TaxaPatio: -1,
                    DpvatExercicio: 0,
                    DpvatAnterior: -1,
                    CodigoServico: 7,
                    Classe: 4,
                    Exercicio: 2018,
                    Parcela: 0,
                    IpvaCotas: '',
                  },
                  {
                    DescricaoServico: 'Postagem do CRLV 2017',
                    ValorAtualizadoFranquia: '19.6400',
                    DataVencimento: '2017-07-18T03:00:00.000Z',
                    DpvatCotas: '',
                    IdDebito: 78994446,
                    Placa: 'ROU8470',
                    IpvaExercicio: -1,
                    IpvaAnterior: -1,
                    LicenciamentoExercicio: 3,
                    LicenciamentoAnterior: 2,
                    TaxaServico: -1,
                    Multas: -1,
                    IpvaParcelamento: -1,
                    TaxaEspecial: -1,
                    TaxaPatio: -1,
                    DpvatExercicio: -1,
                    DpvatAnterior: -1,
                    CodigoServico: 27,
                    Classe: 1,
                    Exercicio: 2017,
                    Parcela: 0,
                    IpvaCotas: '',
                  },
                  {
                    DescricaoServico: 'IPVA 4ª Cota 2017',
                    ValorAtualizadoFranquia: '77.5800',
                    DataVencimento: '2017-07-12T03:00:00.000Z',
                    DpvatCotas: '',
                    IdDebito: 78994827,
                    Placa: 'ROU8470',
                    IpvaExercicio: 1,
                    IpvaAnterior: 1,
                    LicenciamentoExercicio: 1,
                    LicenciamentoAnterior: 1,
                    TaxaServico: -1,
                    Multas: -1,
                    IpvaParcelamento: -1,
                    TaxaEspecial: -1,
                    TaxaPatio: -1,
                    DpvatExercicio: -1,
                    DpvatAnterior: -1,
                    CodigoServico: 129,
                    Classe: 3,
                    Exercicio: 2017,
                    Parcela: 4,
                    IpvaCotas: '20174',
                  },
                  {
                    DescricaoServico: 'IPVA 3ª Cota 2017',
                    ValorAtualizadoFranquia: '77.7400',
                    DataVencimento: '2017-06-12T03:00:00.000Z',
                    DpvatCotas: '',
                    IdDebito: 78994826,
                    Placa: 'ROU8470',
                    IpvaExercicio: 1,
                    IpvaAnterior: 1,
                    LicenciamentoExercicio: 1,
                    LicenciamentoAnterior: 1,
                    TaxaServico: -1,
                    Multas: -1,
                    IpvaParcelamento: -1,
                    TaxaEspecial: -1,
                    TaxaPatio: -1,
                    DpvatExercicio: -1,
                    DpvatAnterior: -1,
                    CodigoServico: 128,
                    Classe: 3,
                    Exercicio: 2017,
                    Parcela: 3,
                    IpvaCotas: '20173',
                  },
                  {
                    DescricaoServico: 'IPVA 2ª Cota 2017',
                    ValorAtualizadoFranquia: '77.9400',
                    DataVencimento: '2017-05-15T03:00:00.000Z',
                    DpvatCotas: '',
                    IdDebito: 78994825,
                    Placa: 'ROU8470',
                    IpvaExercicio: 1,
                    IpvaAnterior: 1,
                    LicenciamentoExercicio: 1,
                    LicenciamentoAnterior: 1,
                    TaxaServico: -1,
                    Multas: -1,
                    IpvaParcelamento: -1,
                    TaxaEspecial: -1,
                    TaxaPatio: -1,
                    DpvatExercicio: -1,
                    DpvatAnterior: -1,
                    CodigoServico: 10,
                    Classe: 3,
                    Exercicio: 2017,
                    Parcela: 2,
                    IpvaCotas: '20172',
                  },
                  {
                    DescricaoServico: 'IPVA 1ª Cota 2017',
                    ValorAtualizadoFranquia: '78.1500',
                    DataVencimento: '2017-04-13T03:00:00.000Z',
                    DpvatCotas: '',
                    IdDebito: 78994824,
                    Placa: 'ROU8470',
                    IpvaExercicio: 1,
                    IpvaAnterior: 1,
                    LicenciamentoExercicio: 1,
                    LicenciamentoAnterior: 1,
                    TaxaServico: -1,
                    Multas: -1,
                    IpvaParcelamento: -1,
                    TaxaEspecial: -1,
                    TaxaPatio: -1,
                    DpvatExercicio: -1,
                    DpvatAnterior: -1,
                    CodigoServico: 9,
                    Classe: 3,
                    Exercicio: 2017,
                    Parcela: 1,
                    IpvaCotas: '20171',
                  },
                  {
                    DescricaoServico: 'Licenciamento Anual 2017',
                    ValorAtualizadoFranquia: '157.0800',
                    DataVencimento: '2017-04-13T03:00:00.000Z',
                    DpvatCotas: '',
                    IdDebito: 78994582,
                    Placa: 'ROU8470',
                    IpvaExercicio: -1,
                    IpvaAnterior: -1,
                    LicenciamentoExercicio: 1,
                    LicenciamentoAnterior: 1,
                    TaxaServico: -1,
                    Multas: -1,
                    IpvaParcelamento: -1,
                    TaxaEspecial: -1,
                    TaxaPatio: -1,
                    DpvatExercicio: -1,
                    DpvatAnterior: -1,
                    CodigoServico: 1,
                    Classe: 1,
                    Exercicio: 2017,
                    Parcela: 0,
                    IpvaCotas: '',
                  },
                  {
                    DescricaoServico: 'Seguro DPVAT 2017 Cota Única',
                    ValorAtualizadoFranquia: '105.6800',
                    DataVencimento: '2017-04-13T03:00:00.000Z',
                    DpvatCotas: '20170',
                    IdDebito: 78994439,
                    Placa: 'ROU8470',
                    IpvaExercicio: -1,
                    IpvaAnterior: -1,
                    LicenciamentoExercicio: 1,
                    LicenciamentoAnterior: 1,
                    TaxaServico: -1,
                    Multas: -1,
                    IpvaParcelamento: -1,
                    TaxaEspecial: -1,
                    TaxaPatio: -1,
                    DpvatExercicio: 1,
                    DpvatAnterior: 1,
                    CodigoServico: 7,
                    Classe: 4,
                    Exercicio: 2017,
                    Parcela: 0,
                    IpvaCotas: '',
                  },
                ],
              },
        };
    }
}